### ISSUE TITLE
非常棒，希望文档和api调用更加清晰

### ISSUE THREAD

**Issue by flopgiggle** [centuryeggs/temperature-chart#1]
非常棒，希望文档和api调用更加清晰

**Comment by junvale** [comment]
感谢鼓励，后续会优化文档。如果你有什么需求或改进的建议也可以提出。

**Comment by junvale** [comment]
已添加更多注释说明 [chore:补充使用说明](https://github.com/centuryeggs/temperature-chart/commit/c72522357ef9d2b64248f29e86c2e521692b5174)
