### ISSUE TITLE
不支持Safari浏览器

### ISSUE THREAD

**Issue by hzj0015** [centuryeggs/temperature-chart#3]
<img width="1287" alt="image" src="https://github.com/centuryeggs/temperature-chart/assets/62981695/078f999a-bd67-4623-88a5-ab7b0cca3247">

**Comment by junvale** [comment]
@hzj0015 
<img width="956" alt="image" src="https://github.com/centuryeggs/temperature-chart/assets/36469823/607a1eed-966e-43a3-b549-09fb42e58eb9">
较新的 16.5.1 版本未发现异常，

**Comment by hzj0015** [comment]
16.5.1版本在哪下载
