### ISSUE TITLE
是否适用于react项目

### ISSUE THREAD

**Issue by changmen1** [centuryeggs/temperature-chart#5]
你好我想请问这个demo适用于 react项目吗

**Comment by junvale** [comment]
@changmen1 使用原生 js 实现的，不受限于框架。可以自行封装组件使用。

**Comment by changmen1** [comment]
已经采用了你的方案，非常感谢，省了很多的时间  就是要把js转成ts

**Comment by junvale** [comment]
> 已经采用了你的方案，非常感谢，省了很多的时间  就是要把js转成ts

很高兴能帮到你
